### ISSUE TITLE
`waku build` error when in monorepo

### ISSUE THREAD

**Issue by himself65** [dai-shi/waku#976] opened 2024-10-18 20:36 UTC
```shell
/Users/himself65/.local/state/fnm_multishells/1113_1729278934946/bin/npm run build

> www@0.0.0 build
> waku build

vite v5.4.9 building SSR bundle for production...
✓ 1744 modules transformed.
✓ built in 1.64s
vite v5.4.9 building SSR bundle for production...
✓ 1808 modules transformed.
✓ built in 1.55s
vite v5.4.9 building SSR bundle for production...
✓ 1748 modules transformed.
x Build failed in 721ms
node:internal/modules/run_main:129
    triggerUncaughtException(
    ^

[commonjs--resolver] Failed to resolve entry for package "https". The package may have incorrect main/module/exports specified in its package.json.
    at packageEntryFailure (file:///Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/vite@5.4.9_@types+node@22.7.5_terser@5.34.1/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:46626:15)
    at resolvePackageEntry (file:///Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/vite@5.4.9_@types+node@22.7.5_terser@5.34.1/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:46623:3)
    at tryNodeResolve (file:///Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/vite@5.4.9_@types+node@22.7.5_terser@5.34.1/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:46439:16)
    at Object.resolveId (file:///Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/vite@5.4.9_@types+node@22.7.5_terser@5.34.1/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:46189:19)
    at Object.handler (file:///Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/vite@5.4.9_@types+node@22.7.5_terser@5.34.1/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:65642:15)
    at file:///Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:20730:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:20630:28)
    at async resolveId (file:///Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:19234:26)
    at async ModuleLoader.resolveId (file:///Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:19663:15)
    at async Object.resolveId (file:///Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/waku@0.21.4_@swc+helpers@0.5.13_@types+node@22.7.5_react-dom@19.0.0-rc-bf7e210c-20241017_reac_fvx3e6vn4nbvqunscnynkb2nbm/node_modules/waku/dist/lib/plugins/vite-plugin-rsc-managed.js:66:30) {
  code: 'PLUGIN_ERROR',
  pluginCode: 'ERR_RESOLVE_PACKAGE_ENTRY_FAIL',
  plugin: 'commonjs--resolver',
  hook: 'resolveId',
  watchFiles: [
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/react-server-dom-webpack@19.0.0-rc-bf7e210c-20241017_react-dom@19.0.0-rc-bf7e210c-20241017_re_57bqax4kx4qy555si4htuvogkq/node_modules/react-server-dom-webpack/server.edge.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/waku@0.21.4_@swc+helpers@0.5.13_@types+node@22.7.5_react-dom@19.0.0-rc-bf7e210c-20241017_reac_fvx3e6vn4nbvqunscnynkb2nbm/node_modules/waku/dist/client.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/waku@0.21.4_@swc+helpers@0.5.13_@types+node@22.7.5_react-dom@19.0.0-rc-bf7e210c-20241017_reac_fvx3e6vn4nbvqunscnynkb2nbm/node_modules/waku/dist/server.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/waku@0.21.4_@swc+helpers@0.5.13_@types+node@22.7.5_react-dom@19.0.0-rc-bf7e210c-20241017_reac_fvx3e6vn4nbvqunscnynkb2nbm/node_modules/waku/dist/router/client.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/pages/_layout.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/pages/note/[noteId].tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/pages/index.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/components/chat-list.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/components/editor.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/components/chat.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/components/external-link.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/components/footer.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/components/empty-screen.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/components/llamaindex.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/components/message.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/components/note-list-preview.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/components/header.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/components/new-note-button.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/components/note-title.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/waku@0.21.4_@swc+helpers@0.5.13_@types+node@22.7.5_react-dom@19.0.0-rc-bf7e210c-20241017_reac_fvx3e6vn4nbvqunscnynkb2nbm/node_modules/waku/dist/minimal/client.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/components/ui/avatar.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/components/ui/card.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/components/ui/button.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/components/ui/badge.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/components/ui/dropdown-menu.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/components/ui/icons.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/components/ui/input.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/components/ui/label.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/components/ui/separator.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/components/ui/sheet.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/components/ui/scroll-area.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/components/ui/textarea.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/components/ui/tooltip.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/components/ui/toast.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/@radix-ui+react-toast@1.2.2_@types+react-dom@18.3.0_@types+react@18.3.11_react-dom@19.0.0-rc-_hgx56dh7nia42geircaluitsum/node_modules/@radix-ui/react-toast/dist/index.mjs',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/ai@3.4.10_openai@4.67.3_zod@3.23.8__react@19.0.0-rc-bf7e210c-20241017_solid-js@1.9.2_sswr@2.1_62aei3syvqh35hb77guppdwrdm/node_modules/ai/rsc/dist/rsc-shared.mjs',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/ai/provider.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/components/ui/toaster.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/components/ui/use-toast.ts',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/ai@3.4.10_openai@4.67.3_zod@3.23.8__react@19.0.0-rc-bf7e210c-20241017_solid-js@1.9.2_sswr@2.1_62aei3syvqh35hb77guppdwrdm/node_modules/ai/rsc/dist/rsc-server.mjs',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/package.json',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/waku@0.21.4_@swc+helpers@0.5.13_@types+node@22.7.5_react-dom@19.0.0-rc-bf7e210c-20241017_reac_fvx3e6vn4nbvqunscnynkb2nbm/node_modules/waku/dist/minimal/server.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/waku@0.21.4_@swc+helpers@0.5.13_@types+node@22.7.5_react-dom@19.0.0-rc-bf7e210c-20241017_reac_fvx3e6vn4nbvqunscnynkb2nbm/node_modules/waku/dist/middleware/context.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/react-server-dom-webpack@19.0.0-rc-bf7e210c-20241017_react-dom@19.0.0-rc-bf7e210c-20241017_re_57bqax4kx4qy555si4htuvogkq/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.production.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/react@19.0.0-rc-bf7e210c-20241017/node_modules/react/jsx-runtime.react-server.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/react-dom@19.0.0-rc-bf7e210c-20241017_react@19.0.0-rc-bf7e210c-20241017/node_modules/react-dom/react-dom.react-server.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/react@19.0.0-rc-bf7e210c-20241017/node_modules/react/react.react-server.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/waku@0.21.4_@swc+helpers@0.5.13_@types+node@22.7.5_react-dom@19.0.0-rc-bf7e210c-20241017_reac_fvx3e6vn4nbvqunscnynkb2nbm/node_modules/waku/dist/lib/middleware/context.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/styles.css',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/pages.gen.ts',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/store/client.ts',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/lib/hooks/chat-scroll-anchor.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/lib/hooks/use-at-bottom.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/lib/hooks/use-enter-submit.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/src/lib/utils/index.tsx',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/packages/www/tailwind.config.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/lucide-react.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/waku@0.21.4_@swc+helpers@0.5.13_@types+node@22.7.5_react-dom@19.0.0-rc-bf7e210c-20241017_reac_fvx3e6vn4nbvqunscnynkb2nbm/node_modules/waku/dist/main.react-server.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/waku@0.21.4_@swc+helpers@0.5.13_@types+node@22.7.5_react-dom@19.0.0-rc-bf7e210c-20241017_reac_fvx3e6vn4nbvqunscnynkb2nbm/node_modules/waku/dist/router/server.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/class-variance-authority@0.7.0/node_modules/class-variance-authority/dist/index.mjs',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/@radix-ui+react-slot@1.1.0_@types+react@18.3.11_react@19.0.0-rc-bf7e210c-20241017/node_modules/@radix-ui/react-slot/dist/index.mjs',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/a-arrow-down.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/a-arrow-up.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/accessibility.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/activity.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/index.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/air-vent.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/a-large-small.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/airplay.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/album.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/alarm-clock-off.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/alarm-smoke.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/alarm-clock.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/align-center-vertical.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/align-center-horizontal.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/align-center.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/align-end-horizontal.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/align-end-vertical.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/align-horizontal-distribute-center.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/align-horizontal-distribute-end.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/align-horizontal-distribute-start.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/align-horizontal-justify-end.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/align-horizontal-justify-center.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/align-horizontal-justify-start.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/align-horizontal-space-around.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/align-horizontal-space-between.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/align-justify.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/align-left.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/align-right.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/align-start-horizontal.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/align-start-vertical.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/align-vertical-distribute-center.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/align-vertical-distribute-end.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/align-vertical-distribute-start.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/align-vertical-justify-center.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/align-vertical-justify-end.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/align-vertical-justify-start.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/align-vertical-space-around.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/align-vertical-space-between.js',
    '/Users/himself65/Code/how-to-create-llm-in-node.js/node_modules/.pnpm/lucide-react@0.453.0_react@19.0.0-rc-bf7e210c-20241017/node_modules/lucide-react/dist/esm/icons/ambulance.js',
    ... 1638 more items
  ]
}

Node.js v20.17.0

Process finished with exit code 1

```

**Comment by himself65** [comment] 2024-10-18 20:49
```
entryPoint ./lib/index.mjs zod
entryPoint lib/index.mjs node-fetch
entryPoint ./lib/esm/index.js formdata-node
entryPoint index.js agentkeepalive
entryPoint dist/abort-controller abort-controller
entryPoint ./lib/esm/index.js form-data-encoder
entryPoint index.js node-domexception
entryPoint dist/event-target-shim event-target-shim
entryPoint lib/public-api.js whatwg-url
entryPoint index.js https

```

**Comment by dai-shi** [comment] 2024-10-19 00:01
If it worked before, it seems like it’s due to the Vite upgrade.

**Comment by dai-shi** [comment] 2024-10-19 10:46
I wasn't able to reproduce the error with just adding `./src/components/func.ts` and importing it from `./src/pages/index.tsx`.

**Comment by himself65** [comment] 2024-10-19 20:04
https://github.com/himself65/waku-issue-976

**Comment by dai-shi** [comment] 2024-10-19 22:09
Is it related with #676 and #684? Sounds different.

**Comment by dai-shi** [comment] 2024-10-20 09:20
nailed down that this is affected with #764 change.

**Comment by himself65** [comment] 2024-10-20 20:22
workaround for now, as discussed in discord

```
$ cat packages/www/vite.config.ts 
export default () => {
  return {
    ssr: {
      resolve: {
        conditions: ["workerd"],
      },
    },
  };
};
```

**Comment by dai-shi** [comment] 2024-12-22 01:06
Do you still have the same issue with all latest versions?

#764 was a good change and if the `workerd` condition is only the reason of the issue, the suggested workaround is the real solution for now.

Closing this especially because it's not tied to monorepo issue.
If the problem persists, please open a new issue.

**Closed by dai-shi** 2024-12-22 01:06 UTC
