### ISSUE TITLE
duplicated chunks in rsc (tailwind styles)

### ISSUE THREAD

**Issue by Aslemammad** [dai-shi/waku#323] opened 2023-12-27 12:49 UTC
large chunks in rsc which can be a short filename instead

![image](https://github.com/dai-shi/waku/assets/37929992/69c84339-8798-4a93-a379-2d781ca3923a)

**Comment by dai-shi** [comment] 2023-12-27 12:58
it's dev only issue, right?

**Comment by Aslemammad** [comment] 2023-12-27 13:02
Nope, it happens in pnpm build also!

**Comment by dai-shi** [comment] 2023-12-27 13:10
Oh, I see.
I saw it's been sent repeatedly in DEV, but does it send the large chunk repeatedly in PRD too?

**Comment by Aslemammad** [comment] 2023-12-27 13:15
the chunk are already embedded in the html PRD, so they're not sent as far as I know (correct me). But in PRD, it's even worse, because many more chunks are being loaded this way.

![image](https://github.com/dai-shi/waku/assets/37929992/7ebfe019-e80c-42c5-8e25-311d01ff92f5)

**Comment by dai-shi** [comment] 2023-12-27 14:24
Oh, that's bad. That's my oversight.
Yes, this is urgent.

Right, those chunks are embedded with SSR and sent over wire with RSC.

**Comment by Aslemammad** [comment] 2023-12-27 14:31
@dai-shi I'm just re-reading the whole source code, do you have any hint that might help? Any filename or function name.

**Comment by Aslemammad** [comment] 2023-12-27 14:39
I guess it's the router/server file.

**Comment by dai-shi** [comment] 2023-12-27 14:42
The large chunks are probably generated with the combination of vite and react. It has nothing to do with router, I guess. (Yeah, it might be good to reproduce the behavior without waku/router and without SSR.)
What I think is related is handler-dev.ts and rsc-renderer.ts.

**Comment by Aslemammad** [comment] 2023-12-27 15:27
- without SSR, there's no issue.

I just started doubting if there's any problem with the chunks since they are RSC and they render on the server and then the serialized result gets injected which has so many tailwind classes, I think this is fair, let me know if I'm wrong.

**Comment by Aslemammad** [comment] 2023-12-27 18:29
The same happens in a nextjs example

![image](https://github.com/dai-shi/waku/assets/37929992/66de4f56-63a2-44ea-b34c-099bb8a8c5a6)

**Comment by dai-shi** [comment] 2023-12-27 23:04
> it's dev only issue, right?

So, back to my original understanding, it was working fine in PRD, but at some point, in DEV, we see duplicated chunks, sending same tailwind styles multiple times in the RSC payload (or embedded in html in SSR).

Do you not observe it anymore?

**Comment by Aslemammad** [comment] 2023-12-28 06:49
> it was working fine in PRD

I see the tailwind chunks in PRD! But yes, it's not duplicated. In dev, only in the first run, they're duplicated; when you reload, it gets fixed. I thought this was an expected behaviour where things get cached, but I guess is wrong.

I think we should change the issue's title, because the chunks and their size are not the issue, rather the duplication is.

**Comment by dai-shi** [comment] 2023-12-28 13:23
Yeah, I think ideally, they shouldn't be duplicated for the first load in DEV.

**Comment by Aslemammad** [comment] 2023-12-28 13:46
I'll get back to this later! If anyone wants to take it meanwhile, don't hesitate!

**Comment by dai-shi** [comment] 2024-01-03 14:59
Hmmm, I'm not confident if it's dev only issue. Further investigation is appreciated.

**Comment by dai-shi** [comment] 2024-01-04 06:38
Another issue is if we disable JS, there's no styles (reported by @himself65 )

It can be a different issue, but I think the root cause is the same.

**Comment by Aslemammad** [comment] 2024-01-04 06:56
> Another issue is if we disable JS, there's no styles (reported by @himself65 )

dev mode or production mode? As far as I guess, this should not happen in production, but expected in dev since we support HMR that way.

**Comment by dai-shi** [comment] 2024-01-04 07:37
I think it's both dev and prd.

**Comment by dai-shi** [comment] 2024-01-04 10:23
Maybe, I'm wrong. It's dev only. Can @himself65 confirm?

**Comment by himself65** [comment] 2024-01-04 17:50
> yeah, dev only.

There is dev css flickering because it loaded later than the JSX.

**Comment by dai-shi** [comment] 2024-01-05 01:46
So, it's the same as the first item in #344. I'm not sure now if it's the same root cause.

**Comment by dai-shi** [comment] 2024-01-08 02:53
@Aslemammad 
> I see the tailwind chunks in PRD! But yes, it's not duplicated.

This looks somewhat duplicated. It might not be tailwind chunks, but bright ones?

<img width="1089" alt="image" src="https://github.com/dai-shi/waku/assets/490574/ff6e4c5f-fa0c-4195-a096-dface8ca2b6e">

**Comment by Aslemammad** [comment] 2024-01-08 09:37
For me, PRD was ok in that sense if I recall correctly

**Comment by dai-shi** [comment] 2024-01-08 10:36
That's what we discussed but it feels duplicated now I see it. I'm not sure if it's reasonable.

**Comment by Aslemammad** [comment] 2024-01-08 13:56
Yes, maybe! but as I saw last time, the result was not as scattered as the dev result was.

**Comment by ojj1123** [comment] 2024-01-21 10:54
> The same happens in a nextjs example

Next.js team is aware of the LARGE chunks so they try to optimize RSC payload.
But yet This optimized chunks are not released

## Reference
https://github.com/vercel/next.js/pull/52028
https://github.com/vercel/next.js/pull/52039
https://github.com/vercel/next.js/pull/52040

**Comment by dai-shi** [comment] 2024-03-13 12:03
Do we still have any issues?
Otherwise, let's close it for now.

**Closed** 2024-08-17 03:59 UTC
Labels: help wanted
