### ISSUE TITLE
CommonJS Default Import missing / DEV MODE

### ISSUE THREAD

**Issue by aheissenberger** [dai-shi/waku#482] opened 2024-02-12 19:44 UTC
ERROR in hydration process in browser - only in **DEV MODE** `pnpm waku dev --with-ssr` - build has no problems:
```
react-server-dom-webpack_client.js?v=0f579180:864 Uncaught SyntaxError: 
The requested module '/node_modules/.pnpm/dayjs@1.11.10/node_modules/dayjs/dayjs.min.js?v=32646099' does not provide an export named 'default' (at get-timezone-offset.mjs?v=32646099:2:8)
```

original [file](https://unpkg.com/browse/@mantine/dates@7.5.2/esm/utils/get-timezone-offset.mjs) - bundled:
```js
'use client';
import dayjs from "/node_modules/.pnpm/dayjs@1.11.10/node_modules/dayjs/dayjs.min.js?v=89918f44";
import timezonePlugin from "/node_modules/.pnpm/dayjs@1.11.10/node_modules/dayjs/plugin/timezone.js?v=89918f44";
import utcPlugin from "/node_modules/.pnpm/dayjs@1.11.10/node_modules/dayjs/plugin/utc.js?v=89918f44";

dayjs.extend(utcPlugin);
dayjs.extend(timezonePlugin);
function getTimezoneOffset(date, timezone) {
    if (timezone) {
        return dayjs(date).tz(timezone).utcOffset() + date.getTimezoneOffset();
    }
    return 0;
}

export {getTimezoneOffset};
```

The package [`dayjs`](https://unpkg.com/browse/dayjs@1.11.10/) package.json does not provide a `type` nor does it provide `exports`. An [`esm` folder](https://unpkg.com/browse/dayjs@1.11.10/esm/) exists but is not detected by Vitejs.

The script does not fail with `import dayjs from`, it fails with the **deep** import from plugin folder:
`import timezonePlugin from "/node_modules/.pnpm/dayjs@1.11.10/node_modules/dayjs/plugin/timezone.js?v=89918f44";`

current vite config:
```ts
import { defineConfig } from 'vite';

export default defineConfig(({ mode }) => ({
  ...({
    optimizeDeps: {
      exclude: ['@mantine/core','@mantine/hooks'],
    },
    ssr: {
      noExternal: ['@mantine/core','@mantine/hooks'],
    },
  }),
}));
```

[tsconfig.node.json](https://github.com/dai-shi/waku/files/14250174/tsconfig.node.json)
[tsconfig.json](https://github.com/dai-shi/waku/files/14250175/tsconfig.json)

**How can a change of vite DEV MODE config fix this problem?**

**Comment by aheissenberger** [comment] 2024-02-12 20:10
same problem with `lodash`:

```
react-server-dom-webpack_client.js?v=445c577a:864 Uncaught SyntaxError: The requested module '/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/get.js?v=b868b311' does not provide an export named 'default' (at DataUtils.js?v=b868b311:3:8)
```

**Comment by dai-shi** [comment] 2024-02-13 00:20
> it fails with the **deep** import from plugin folder

Sounds like it's extremely hard to solve. Hoped externalizing would help.

```
$ mkdir dayjs-test
$ cd dayjs-test 
$ npm init -y
$ npm i dayjs
$ cat test.mjs
import timezonePlugin from "dayjs/plugin/timezone.js";

console.log(timezonePlugin);
$ node test.mjs
[Function (anonymous)]
```
Hmm, this works. We'd need someone experienced with Vite.

**Comment by campbellman** [comment] 2024-02-13 03:15
I was able to prevent the lodash error after installing `vite-plugin-cjs-interop` and adding the following `vite.config.ts` file:

```typescript
import { cjsInterop } from 'vite-plugin-cjs-interop';

export default {
  plugins: [
    cjsInterop({
      // List of CJS dependencies that require interop
      dependencies: ['lodash'],
    }),
  ],
};
```

* `vite-plugin-cjs-interop` source: https://github.com/cyco130/vite-plugin-cjs-interop
* comment that led me there: https://github.com/antfu/vite-ssg/issues/266#issuecomment-1605275438

I wasn't able to reproduce the dayjs issue myself so I'm curious if this fixes that as well too @aheissenberger.

This doesn't seem like a great long term solution. I'll continue looking further into waku's internal config.

**Comment by dai-shi** [comment] 2024-02-13 07:33
looks good to me for the current workaround > cjsInterop

**Comment by aheissenberger** [comment] 2024-02-13 10:35
**no improvement** - I tested the plugin with this config:
```js
cjsInterop({
      // List of CJS dependencies that require interop
      dependencies: ['lodash','lodash/**','dayjs','dayjs/**'],
}),
```

To be clear - the problem exists only in the javascript code which is loaded in **dev mode** in the **hydration process**. The server side rendered code works without an error and outputs the correct static html in dev mode, then the hydration kicks in and the error is thrown in the browser.

I think the logic of the plugin could help but the plugin seems not to be called to transform the code required by the frontend in the hydration process. The documentation of the plugin states that it will only be called during the SSR process.

I removed the  vite cache in `./node_modules/.vite` before every test - here is a grep of all that happend with `dayjs` in the vitejs debug output:
```log

```

As a next step I will try to create a simple test setup without the Mantine UI framework

**Comment by aheissenberger** [comment] 2024-02-13 11:17
I found this additional options for the plugin - but then the plugin crashes:
```js
plugins: [
    cjsInterop({
      // List of CJS dependencies that require interop
      dependencies: [
      'dayjs'
    ],
      client: true,
      apply:'serve'
    }),
  ],
```

I debugged the crash of the `acorn` javascript parser and fixed it by modifying the cjs-interop plugin to ignoring code where the id ends with `.css`.

The original error is gone, but I have now an other error:
```
Uncaught TypeError: Cannot read properties of null (reading 'use')
    at use (chunk-FJJXHVDL.js?v=fe4df551:1736:29)
    at Children (client.js?v=fe4df551:126:29)
    at renderWithHooks (chunk-6XPIBFK3.js?v=b35bb809:8402:26)
    at updateFunctionComponent (chunk-6XPIBFK3.js?v=b35bb809:12140:28)
    at mountLazyComponent (chunk-6XPIBFK3.js?v=b35bb809:12453:23)
    at beginWork$1 (chunk-6XPIBFK3.js?v=b35bb809:13568:22)
    at HTMLUnknownElement.callCallback2 (chunk-6XPIBFK3.js?v=b35bb809:14917:22)
    at Object.invokeGuardedCallbackImpl (chunk-6XPIBFK3.js?v=b35bb809:14942:24)
    at invokeGuardedCallback (chunk-6XPIBFK3.js?v=b35bb809:14982:37)
    at beginWork (chunk-6XPIBFK3.js?v=b35bb809:19031:15)
```

**Comment by Aslemammad** [comment] 2024-07-21 14:44
Can we close this since it's fixed in the upstream?

**Comment by Aslemammad** [comment] 2024-07-21 14:44
Can we close this since it's fixed in the upstream?

**Closed** 2024-07-21 22:32 UTC
Labels: help wanted
