### ISSUE TITLE
tsconfig paths can't be loaded

### ISSUE THREAD

**Issue by tclain-pillar** [dai-shi/waku#744] opened 2024-06-12 22:51 UTC
When trying to import a client component using typescript path alias, I get the following error on screen
```
TypeError: Failed to fetch dynamically imported module: http://localhost:3002/src/components/counter.tsx
```
The main page displays for a second then fails with the error above.

The console has this error:
```
6:41:42 PM [vite] Pre-transform error: Failed to load url /react (resolved id: /Users/tclain/z/repro/paths/react) in /Users/tclain/z/repro/paths/src/components/counter.tsx. Does the file exist?
6:41:42 PM [vite] Pre-transform error: Failed to load url /react/jsx-dev-runtime (resolved id: /Users/tclain/z/repro/paths/react/jsx-dev-runtime) in /Users/tclain/z/repro/paths/src/components/counter.tsx. Does the file exist?
```

**pnpm build** gives:

```
node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^

[Error: [vite:load-fallback] Could not load /Users/tclain/z/repro/paths/react/jsx-runtime (imported by src/pages/index.tsx): ENOENT: no such file or directory, open '/Users/tclain/z/repro/paths/react/jsx-runtime'] {
  errno: -2,
  code: 'PLUGIN_ERROR',
  syscall: 'open',
  path: '/Users/tclain/z/repro/paths/react/jsx-runtime',
  pluginCode: 'ENOENT',
  plugin: 'vite:load-fallback',
  hook: 'load',
  watchFiles: [
    '/Users/tclain/z/repro/paths/node_modules/.pnpm/react-server-dom-webpack@19.0.0-beta-e7d213dfb0-20240507_react-dom@19.0.0-beta-e7d213dfb0-202_ozu3bnomygrcqdvc7ehsn47hbi/node_modules/react-server-dom-webpack/server.edge.js',
    '/Users/tclain/z/repro/paths/node_modules/.pnpm/waku@0.20.2_@types+node@20.14.2_react-dom@19.0.0-beta-e7d213dfb0-20240507_react@19.0.0-beta-e_ufvglycicg6npnae675v5tqo44/node_modules/waku/dist/server.js',
    '/Users/tclain/z/repro/paths/src/pages/_layout.tsx',
    '/Users/tclain/z/repro/paths/node_modules/.pnpm/waku@0.20.2_@types+node@20.14.2_react-dom@19.0.0-beta-e7d213dfb0-20240507_react@19.0.0-beta-e_ufvglycicg6npnae675v5tqo44/node_modules/waku/dist/router/client.js',
    '/Users/tclain/z/repro/paths/src/pages/index.tsx',
    '/Users/tclain/z/repro/paths/node_modules/.pnpm/waku@0.20.2_@types+node@20.14.2_react-dom@19.0.0-beta-e7d213dfb0-20240507_react@19.0.0-beta-e_ufvglycicg6npnae675v5tqo44/node_modules/waku/dist/client.js',
    '/Users/tclain/z/repro/paths/src/components/counter.tsx',
    '/Users/tclain/z/repro/paths/src/pages/about.tsx',
    '/Users/tclain/z/repro/paths/src/components/footer.tsx',
    '/Users/tclain/z/repro/paths/src/components/header.tsx',
    '/Users/tclain/z/repro/paths/package.json'
  ]
}
```

## Reproduction
**I repro-ed with the following steps**

- `pnpm create waku@latest`
- pnpm i
- pnpm add vite-tsconfig-paths
- added a vite.config.ts

```
import tsconfigPaths from "vite-tsconfig-paths";
import { fileURLToPath } from "node:url";

/** @type {import('vite').UserConfig} */
export default {
  plugins: [
    tsconfigPaths({
      root: fileURLToPath(new URL(".", import.meta.url)),
    }),
  ],
};
```

- added paths to tsconfig.json

```json
{
  "compilerOptions": {
    "strict": true,
    "target": "esnext",
    "downlevelIteration": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "skipLibCheck": true,
    "noUncheckedIndexedAccess": true,
    "exactOptionalPropertyTypes": true,
    "types": ["react/experimental"],
    "jsx": "react-jsx",
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  }
}
```

Change

```
import { Counter } from "../components/counter";
```

to 
```
import { Counter } from "@/components/counter";
```

Things I tried:
- migrate to 0.21.0-alpha-1  (same error)
- use vite `resolve.alias` directly. fails as soon as I import a client component

repro repo: https://github.com/tclain-pillar/repro-waku-ts-paths

**Comment by dai-shi** [comment] 2024-06-13 10:55
Does this example help?
https://github.com/dai-shi/waku/tree/main/examples/13_path-alias

**Comment by tclain** [comment] 2024-06-13 18:15
Hi ! the example works but uses the low level API with defineEntries (I don't see any docs, the API is a bit cryptic)

as soon as using the pages directory with the minimal steps above. it does fail

**Comment by dai-shi** [comment] 2024-06-13 23:21
Hmm, it looks like more complicated than I thought.
I wonder if @himself65 has any ideas.

> (I don't see any docs, the API is a bit cryptic)

Well, it's not for everybody, but I would like to learn how it feels cryptic... The docs are https://github.com/dai-shi/waku/blob/main/docs/minimal-api.mdx, but it's also "minimal". I agree it's not super developer friendly, because it's not.

**Comment by jackeydou** [comment] 2024-09-28 06:53
Hi, I have the same issue, and solve it by changing vite.config.ts, not use `vite-tsconfig-paths`. I think there are some compatibility issues with vite-tsconfig-paths.


``` vite.config.mts
// import tsconfigPaths from 'vite-tsconfig-paths';
import { fileURLToPath } from 'node:url';

/** @type {import('vite').UserConfig} */
export default {
  // plugins: [
  //   tsconfigPaths(),
  // ],
  resolve: {
    alias: {
      "@": fileURLToPath(new URL('./src', import.meta.url))
    }
  }
};

```

**Comment by dai-shi** [comment] 2024-09-28 07:03
@jackeydou Thanks for investigating.

@himself65 Does that sound reasonable?

**Comment by jackeydou** [comment] 2024-09-28 07:06
> @jackeydou Thanks for investigating.
> 
> @himself65 Does that sound reasonable?

I am not very familiar with vite and its ecosystem, otherwise I could help with further debugging.

**Comment by himself65** [comment] 2024-09-28 07:37
I will check this today

**Comment by himself65** [comment] 2024-09-28 07:40
I can reproduce this

```
/Users/himself65/Code/waku-issue/src/pages/index.tsx. Does the file exist?
12:39:39 AM [vite] Error when evaluating SSR module /src/pages/index.tsx:
|- Error: Failed to load url @/components/counter (resolved id: @/components/counter) in /Users/himself65/Code/waku-issue/src/pages/index.tsx. Does the file exist?
    at loadAndTransform (file:///Users/himself65/Code/waku-issue/node_modules/.pnpm/vite@5.4.4/node_modules/vite/dist/node/chunks/dep-BEhTnQAI.js:51857:17)
    at async instantiateModule (file:///Users/himself65/Code/waku-issue/node_modules/.pnpm/vite@5.4.4/node_modules/vite/dist/node/chunks/dep-BEhTnQAI.js:52816:44)

Cannot process RSC Error: Failed to load url @/components/counter (resolved id: @/components/counter) in /Users/himself65/Code/waku-issue/src/pages/index.tsx. Does the file exist?
    at loadAndTransform (file:///Users/himself65/Code/waku-issue/node_modules/.pnpm/vite@5.4.4/node_modules/vite/dist/node/chunks/dep-BEhTnQAI.js:51857:17)
    at async instantiateModule (file:///Users/himself65/Code/waku-issue/node_modules/.pnpm/vite@5.4.4/node_modules/vite/dist/node/chunks/dep-BEhTnQAI.js:52816:44) {
  code: 'ERR_LOAD_URL'
}
```

**Comment by himself65** [comment] 2024-09-28 07:40
I'm guessing we didn't load vite config correctly somewhere

**Comment by himself65** [comment] 2024-09-28 08:10
<img width="921" alt="image" src="https://github.com/user-attachments/assets/13c4c8ce-24f4-4de8-92c0-03529f8c84bc">

The second paramete is a set of function? But it should be string

**Comment by himself65** [comment] 2024-09-28 08:21
I feel it's related to https://github.com/aleclarson/vite-tsconfig-paths/issues/135

**Comment by himself65** [comment] 2024-09-28 08:45
it's their bug, remove `baseUrl` will fix the issue.

@dai-shi could close this issue

Realted Code: https://github.com/aleclarson/vite-tsconfig-paths/blob/5c9477078d3a913ade563b168ff4a9ccace187a2/src/index.ts#L228

**Comment by himself65** [comment] 2024-09-28 08:55
I think the real reason is inside `initialModules`, it will presever the origial id for a file if it includes alias (plugin will load it before vite analysis the code path). So `react` will be still `react` instead of `node_modules/path/to/react`

**Comment by dai-shi** [comment] 2024-09-30 01:27
So, is it a bug on our end?

**Comment by himself65** [comment] 2024-09-30 05:22
> So, is it a bug on our end?

Kind of? Because I don't think `initialModules` is the suggested solution from vite. This might cause some plugin are called before than vite internal laoding mechanism, that's might why id is `react` instead of `path/to/node_modules/react`

**Comment by dai-shi** [comment] 2024-10-03 00:10
@Aslemammad

**Comment by himself65** [comment] 2024-10-03 16:52
giving some more context:

In normal vite playground, for [this line of code](https://github.com/aleclarson/vite-tsconfig-paths/blob/5c9477078d3a913ade563b168ff4a9ccace187a2/src/index.ts#L228), id will be `path/to/node_modules/id`, but in waku it's just `id`

**Comment by Aslemammad** [comment] 2024-10-13 04:57
I just created a fresh waku template `pnpm create waku@latest`, adding all those steps for reproduction, but now apparently it's working.

Can anyone verify that?

**Comment by dai-shi** [comment] 2024-12-13 08:10
Please open a new issue if the problem still persists.

**Closed by dai-shi** 2024-12-13 08:10 UTC
Labels: help wanted
